services:
  moneyapp:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SERVER_SECRET_KEY=${SERVER_SECRET_KEY}
    volumes:
      - ./my_data_folder:/app/data     
      - ./my_secrets_folder:/app/secrets 
    restart: unless-stopped